spring:
  application:
    name: kotlin-web-mvc
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
